package com.congred.statistics.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.congred.statistics.bean.ClientUsingLogData;
import com.congred.statistics.bean.EventData;

import com.congred.statistics.db.ClientUsingLogDataDao;
import com.congred.statistics.db.EventDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig clientUsingLogDataDaoConfig;
    private final DaoConfig eventDataDaoConfig;

    private final ClientUsingLogDataDao clientUsingLogDataDao;
    private final EventDataDao eventDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        clientUsingLogDataDaoConfig = daoConfigMap.get(ClientUsingLogDataDao.class).clone();
        clientUsingLogDataDaoConfig.initIdentityScope(type);

        eventDataDaoConfig = daoConfigMap.get(EventDataDao.class).clone();
        eventDataDaoConfig.initIdentityScope(type);

        clientUsingLogDataDao = new ClientUsingLogDataDao(clientUsingLogDataDaoConfig, this);
        eventDataDao = new EventDataDao(eventDataDaoConfig, this);

        registerDao(ClientUsingLogData.class, clientUsingLogDataDao);
        registerDao(EventData.class, eventDataDao);
    }
    
    public void clear() {
        clientUsingLogDataDaoConfig.clearIdentityScope();
        eventDataDaoConfig.clearIdentityScope();
    }

    public ClientUsingLogDataDao getClientUsingLogDataDao() {
        return clientUsingLogDataDao;
    }

    public EventDataDao getEventDataDao() {
        return eventDataDao;
    }

}
